import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: '#f5f5f5',
        'surface-dim': '#ecd5d3',
        'surface-bright': '#fff8f7',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#fff0ef',
        'surface-container': '#ffe9e7',
        'surface-container-high': '#fbe3e1',
        'surface-container-highest': '#f5dddb',
        'on-surface': '#251818',
        'on-surface-variant': '#584140',
        'inverse-surface': '#3b2d2c',
        'inverse-on-surface': '#ffedeb',
        outline: '#8c706f',
        'outline-variant': '#e0bfbd',
        'surface-tint': '#ae2f34',
        primary: '#ae2f34',
        'on-primary': '#ffffff',
        'primary-container': '#ff6b6b',
        'on-primary-container': '#6d0010',
        'inverse-primary': '#ffb3b0',
        'primary-fixed': '#ffdad8',
        'primary-fixed-dim': '#ffb3b0',
        'on-primary-fixed': '#410006',
        'on-primary-fixed-variant': '#8c1520',
        secondary: '#535f72',
        'on-secondary': '#ffffff',
        'secondary-container': '#d4e0f7',
        'on-secondary-container': '#576377',
        tertiary: '#006c48',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#00b179',
        'on-tertiary-container': '#003b26',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#f5f5f5',
        'on-background': '#251818',
        'surface-variant': '#f5dddb',
        success: '#2ECC71',
        warning: '#F1C40F',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        'full': '9999px',
      },
      spacing: {
        xs: '4px',
        lg: '40px',
        base: '8px',
        sm: '12px',
        md: '24px',
        'container-max': '440px',
      },
      fontFamily: {
        sans: ['Manrope', 'Noto Sans', 'sans-serif'],
        'headline-md': ['Manrope', 'sans-serif'],
        'button-text': ['Manrope', 'sans-serif'],
        'display-logo': ['Manrope', 'sans-serif'],
        'body-lg': ['Manrope', 'sans-serif'],
        'label-md': ['Manrope', 'sans-serif'],
        'body-sm': ['Manrope', 'sans-serif'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'button-text': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'display-logo': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
      },
      boxShadow: {
        sm: '0 1px 3px rgba(0, 0, 0, 0.06)',
        DEFAULT: '0 4px 20px rgba(0, 0, 0, 0.05)',
        lg: '0 10px 40px rgba(0, 0, 0, 0.08)',
      },
      transitionDuration: {
        DEFAULT: '250ms',
      },
      transitionTimingFunction: {
        DEFAULT: 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
};

export default config;
